---
openapi: 3.0.1
info:
  title: Fundoo Notes API
  version: v1
paths: {}
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- Bearer: []
